azerothcore/mod-progression-system

0/disables.sql
zero/disables.sql

related https://github.com/azerothcore/azerothcore-wotlk/issues/5861

feat(ZERO): initial dungeon/raid disables

---

0/creature_template.sql
80/creature_template.sql

Close https://github.com/azerothcore/progression-system/issues/18

chore: disable npcs vendor arena season 7

---

src/Bracket_60_2/scripts/WorldBosses/boss_lord_kazzak.cpp

1. Not build tested
2. Not ingame tested

fix(Core/Scripts) Mark of Kazzak selector

---

src/Bracket_60_2/sql/world/progression_60_2_onyxia.sql
src/Bracket_80_7/sql/world/revert_progression_80_7_onyxia.sql

Co-Authored-By: temperrr <temperrr@users.noreply.github.com>

fix: Onyxia's melee damage

---

src/Bracket_0/sql/world/progression_0_player_factionchange_items.sql

- Closes https://github.com/azerothcore/mod-progression-system/issues/176
- Closes https://github.com/chromiecraft/chromiecraft/issues/3023

fix: Champion's Sanctuary set on faction change

---

src/Bracket_60_2/sql/world/progression_60_2_onyxia.sql

Closes https://github.com/chromiecraft/chromiecraft/issues/2124

fix: Onyxia's Draconic for Dummies

---

src/Bracket_60_2/sql/world/progression_60_2_onyxia.sql

fix: Onyxia Loot Adjustment

---

src/Bracket_60_2/sql/world/progression_60_2_kazzak.sql

Closes: https://github.com/azerothcore/mod-progression-system/issues/197
Closes:  https://github.com/chromiecraft/chromiecraft/issues/3251

Fix (DB/Loot): Kazzak should drop empyrean demolisher

---

src/Bracket_60_2/scripts/OnyxiasLair/boss_onyxia.cpp

Not tested.
Closes https://github.com/chromiecraft/chromiecraft/issues/3030

fix: Onyxia phase 2 to 3 cancels Deep Breath

---

src/Bracket_60_2_A/scripts/BlackwingLair/boss_chromaggus.cpp

https://github.com/azerothcore/azerothcore-wotlk/pull/11501

chore(Scripts/BlackwingLair): Update Chromaggus script

---

src/Bracket_61_64/sql/world/progression_61_64_npc_vendor.sql

https://github.com/azerothcore/mod-progression-system/issues/175

Set Original Price 50-59 PVP Items

---

src/Bracket_50_59_2/scripts/BlackrockSpire/boss_drakkisath.cpp

Related: https://github.com/azerothcore/azerothcore-wotlk/pull/12992

refactor(Scripts/BlackrockSpire): fix code style for threat functions

---

src/Bracket_60_2_1/scripts/OnyxiasLair/boss_onyxia.cpp

Fix for https://github.com/azerothcore/azerothcore-wotlk/pull/13146

fix(Script/Onyxia): code style for threat functions

---

src/Bracket_61_64/sql/world/progression_61_64_attunement_key_recovery.sql
src/Bracket_70_6_1/sql/world/progression_61_64_attunement_key_recovery_down.sql

Shattered Halls: Blacksmith Trainer in Hellfire Peninsula
Karazhan: Archmage Alturus
Tempest Keep and Arcatraz: A'dal

(SQL): Add key recovery gossip options for TBC attunements

---

src/Bracket_61_64/sql/world/progression_61_64_gameobject_loot_template_nightmare_seed.sql
src/Bracket_71_74/sql/world/progression_61_64_gameobject_loot_template_nightmare_seed_down.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/4592

(SQL): Add Nightmare Seed to Nightmare Vine loot table

---

src/Bracket_61_64/sql/world/progression_61_64_skinning_loot_template_SwampGas.sql
src/Bracket_70_5/sql/world/progression_61_64_skinning_loot_template_SwampGas_down.sql

- Closes https://github.com/azerothcore/mod-progression-system/issues/282
- Closes https://github.com/chromiecraft/chromiecraft/issues/4730

(SQL): Change Swamp Gas to drop Mote of Life instead of Mote of Water until ZA

---

src/Bracket_65_69/sql/world/progression_65_69_creature_onkill_reputation_SethekkHalls.sql
src/Bracket_70_1_1/sql/world/progression_65_69_creature_onkill_reputation_SethekkHalls_down.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/4764
- Closes https://github.com/azerothcore/mod-progression-system/issues/287

Prevent reputation gained from Sethekk Halls to go beyond Honored

---

src/Bracket_0/sql/world/progression_0_creature_undercity_guardian.sql
src/Bracket_80_4_1/sql/world/progression_0_creature_undercity_guardian_down.sql

- Closes https://github.com/azerothcore/mod-progression-system/issues/292
Wait until https://github.com/azerothcore/azerothcore-wotlk/pull/14827 is merged

Replace Kor'Kron Overseer with Undercity Guardian until ICC

---

src/Bracket_1_19/scripts/events/love_in_air.cpp

Closes https://github.com/chromiecraft/chromiecraft/issues/4940

fix: Fix Apothecary Trio summoning adds out of combat on wipe

---

src/Bracket_40_49/sql/world/progression_40_49_gossip_menu_option.sql
src/Bracket_50_59_1/sql/world/progression_50_59_1_gossip_menu_option.sql
src/Bracket_60_1_1/sql/world/progression_60_1_1_gossip_menu_option.sql
src/Bracket_61_64/sql/world/progression_61_64_gossip_menu_option.sql

Add New Dual Spec Bracket

---

src/Bracket_50_59_2/scripts/BlackrockSpire/instance_blackrock_spire.cpp
src/Bracket_60_1_2/scripts/MoltenCore/instance_molten_core.cpp
src/Bracket_60_2_1/scripts/OnyxiasLair/instance_onyxias_lair.cpp

Merge after https://github.com/azerothcore/azerothcore-wotlk/pull/14977

fix: build after instance load/save rewrite

---

src/Bracket_70_1_2/sql/world/progression_61_64_npc_vendor_Geras_down_1.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/5735

Adjust G'eras in TBC to sell Phase 1-3 idols

---

src/Bracket_1_19/sql/world/progression_1_19_world_event_Ahune.sql
src/Bracket_80_1/sql/world/progression_1_19_world_event_Ahune_down.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/5841
187892 is Normal
188124 is Heroic

(SQL): Add missing Ahune Heroic loot

---

src/Bracket_70_3_1/sql/world/progression_70_3_1_unnerf_t4_loot.sql

Reverts azerothcore/mod-progression-system#345

Revert "Revert "fix: progression loot maulgar magtheridon and gruul""

---

src/Bracket_70_3_1/sql/world/progression_70_3_1_loot_t5.sql
src/Bracket_80_1/sql/world/progression_70_3_1_loot_t5_down.sql

Closes https://github.com/chromiecraft/chromiecraft/issues/6424

fix(SSC/Loot): Bosses should drop 2 pieces of t5 until wotlk

---

src/Bracket_70_2_1/sql/world/progression_0_creature_loot_template_Badge_of_Justice_Phase1.sql
src/Bracket_70_5/sql/world/progression_0_creature_loot_template_Badge_of_Justice_Phase1_down.sql

Closes https://github.com/azerothcore/mod-progression-system/issues/365

fix: Remove Badge of Justice from SSC

---

conf/progression_system.conf.dist
src/Bracket_70_3_2/Bracket_70_3_2_loader.cpp
src/Bracket_70_3_2/scripts/the_eye.cpp

- Closes https://github.com/chromiecraft/chromiecraft/issues/6777

fix(TheEye): make sure kael'thas is blocked off until all 3 prior bosses die

---

src/Bracket_71_74/sql/world/progression_71_74_creature_loot_template_kara_enchants_100.sql

fix(SQL): progression_71_74_creature_loot_template_kara_enchants_100 mysql error

---

src/Bracket_70_3_1/sql/world/progression_70_3_1_smart_scripts_ssc.sql
src/Bracket_71_74/sql/world/progression_70_3_1_smart_scripts_ssc_down.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18824
- Closes https://github.com/chromiecraft/chromiecraft/issues/6590

(SQL): Implement scrapped Coilfang Priestess mechanic
