azerothcore/mod-progression-system

65-69/disables.sql
70/disables.sql

Magister's Terrace was released as a catch-up dungeon alongside T6, just before Sunwell Plateau.

chore(disables): Split T6 and move Magister's Terrace

---

50-59/custom_rdf_satchels.sql

Co-authored-by: Ragelezz <Ragelezz@users.noreply.github.com>
Currently there seems to be a problem with mincount and maxcount.  When chosing 3 and 5 respectively it always drops 5.
Will need some further investigation, but for now and for the bracket release this works.
Closes: #28

Add custom loot to +50 loot satchels

---

50-59/disables.sql

Since the npc was momentarily removed by the progression, we also disabled the quest, to avoid confusing players looking for the npc.

Disable quest 8283

---

src/Bracket_60_1/sql/world/progression_60_1_mail_level_rewards.sql
src/Bracket_71_74/sql/world/progression_71_74_npc_vendor - kopia.sql

Disables sending flight master notices to level 60 characters.
SQL content tested.
**SQL automatic loading not tested.**
**SQL automatic loading/Reenabling it during the level 71 bracket not tested. (should it be enable in that bracket?)**
Closes https://github.com/azerothcore/mod-progression-system/issues/75

fix(MOD): Disable sending flight trainer mails at level 60

---

conf/progression_system.conf.dist
src/Bracket_60_1_A/Bracket_60_1_A_loader.cpp
src/Bracket_60_1_A/scripts/MoltenCore/instance_molten_core.cpp
src/Bracket_60_1_A/scripts/MoltenCore/molten_core.h
src/Bracket_60_1_A/sql/world/progression_60_1_A_MC_firelord_runes.sql
src/Bracket_70_4/sql/world/revert_progression_60_1_A_MC_firelord_runes.sql

Implement the possibility to enable manual dousing of the firelord runes, allowing us to mimmick the classic retail mechanic.
Added a config option to allow us to switch back to the other method if necessary:
```
ProgressionSystem.60.MoltenCore.ManualRuneHandling = 1 -- Manual handling (requires dousing)
ProgressionSystem.60.MoltenCore.ManualRuneHandling = 0 -- Auto handling (WotLK's default, automatic when bosses are defeated)
```
Crash recovery:
- After crashes, the runes for defeated bosses are set to active as default, so players don't have to douse them again.

Implement support for manual handling of Firelord Runes (related to Poisoned Water quest chain)

---

src/Bracket_60_2/sql/world/progression_60_2_the_masquerade.sql
src/Bracket_80_7/sql/world/revert_progression_60_2_the_masquerade.sql

Add missing gossip option to Ragged John's changed The Masquerade gossip menu.
Closes https://github.com/chromiecraft/chromiecraft/issues/2925
Locally tested and working:

Fix Mother's Milk gossip option

---

src/Bracket_0/sql/world/progression_0_disables.sql
src/Bracket_80_7/sql/world/revert_progression_80_7_onyxia.sql

Closes https://github.com/chromiecraft/chromiecraft/issues/3614
As of right now, dying to Onyxia in her level 60 form will count as a death to her level 80 form. This PR removes that statistic until (What I think is) the appropriate bracket is reached.
Tested the disable query on its own (Without the progression module) on local AC, did count as a 10-player raid death, but not as a Lich King boss death.

Add disable for death to Onyxia statistic until LK bracket.

---

src/Bracket_60_3_2/sql/progression_60_3_2_scarab_lord_quests.sql

Align with VMangos and others Classic DBs.
Close: https://github.com/chromiecraft/chromiecraft/issues/4037

fix(DB/GameObjects): Tweak drop rates of nightmare fragments

---

src/Bracket_61_64/sql/world/progression_61_64_item_template_revered_heroic_keys.sql
src/Bracket_70_3_1/sql/world/progression_61_64_item_template_revered_heroic_keys_down.sql

Tested ingame. Requires cleared cache to reflect changes.

(SQL): Make TBC Heroic Dungeons keys require Revered

---

src/Bracket_61_64/sql/world/progression_61_64_skinning_loot_template_SwampGas.sql
src/Bracket_70_5/sql/world/progression_61_64_skinning_loot_template_SwampGas_down.sql

Reverts azerothcore/mod-progression-system#283
With this revert it'll follow Classic Progression.
To restore, run: 
```
UPDATE `skinning_loot_template` SET `Item`=22578 WHERE `Entry`=80200 AND `Item`=22575;
```

Revert "(SQL): Change Swamp Gas to drop Mote of Life instead of Mote of Water until ZA"

---

src/Bracket_61_64/sql/world/progression_61_64_attunement_key_recovery.sql
src/Bracket_70_6_1/sql/world/progression_61_64_attunement_key_recovery_down.sql

Please run:
```
-- Rohok (Shattered Halls - Horde)
DELETE FROM `gossip_menu_option` WHERE (`MenuID` = 8760);
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 15) AND (`SourceGroup` = 8760);
UPDATE `creature_template` SET `AIName` = '' WHERE `entry` = 16583;
DELETE FROM `smart_scripts` WHERE (`entryorguid` = 16583) AND (`source_type` = 0) AND (`id` IN (0, 1));
-- Dumphry (Shattered Halls - Alliance)
DELETE FROM `gossip_menu_option` WHERE (`MenuID` = 8254);
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 15) AND (`SourceGroup` = 8254);
UPDATE `creature_template` SET `AIName` = '' WHERE `entry` = 21209;
DELETE FROM `smart_scripts` WHERE (`entryorguid` = 21209) AND (`source_type` = 0) AND (`id` IN (0, 1));
```
If I cannot find a fix for it I'll add it to the vendor with …

Fix Rohok and Dumphry not being trainers

---

src/Bracket_61_64/sql/world/progression_61_64_faction_Netherwing.sql
src/Bracket_61_64/sql/world/progression_61_64_faction_ShatariSkyguard.sql
src/Bracket_70_3_2/sql/world/progression_61_64_faction_ShatariSkyguard_down.sql
src/Bracket_70_4_1/sql/world/progression_61_64_faction_Netherwing_down.sql

Please run to reset your DB:
```
DELETE FROM `creature_loot_template` WHERE `Item`=32388 AND `Entry` IN (21644, 21649, 21650, 21911, 23066, 23067, 23068);
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(21644, 32388, 0, 33, 0, 1, 0, 1, 1, 'Skettis Wing Guard - Shadow Dust'),
(21649, 32388, 0, 33, 0, 1, 0, 1, 1, 'Skettis Windwalker - Shadow Dust'),
(21650, 32388, 0, 33, 0, 1, 0, 1, 1, 'Skettis Talonite - Shadow Dust'),
(21911, 32388, 0, 33, 0, 1, 0, 1, 1, 'Skettis Soulcaller - Shadow Dust'),
(23066, 32388, 0, 33, 0, 1, 0, 1, 1, 'Talonpriest Ishaal - Shadow Dust'),
(23067, 32388, 0, 33, 0, 1, 0, 1, 1, 'Talonpriest Skizzik - Shadow Dust'),
(23068, 32388, 0, 33, 0, 1, 0, 1, 1, …
```

(SQL): Use new disables type to disable loot drops.

---

src/Bracket_70_2_1/sql/world/progression_0_creature_loot_template_Badge_of_Justice_Phase1.sql
src/Bracket_70_3_1/sql/world/progression_70_3_1_unnerf_t4_loot.sql

closes https://github.com/chromiecraft/chromiecraft/issues/5930
1 token currently
2 tokens when serpentshrine opens 
down from 3 tokens each all the time

fix: progression loot maulgar magtheridon and gruul

---

src/Bracket_70_2_2/sql/world/progression_0_creature_loot_template.sql
src/Bracket_70_2_2/sql/world/progression_0_creature_loot_template_kara_enchants.sql
src/Bracket_71_74/sql/world/progression_71_74_creature_loot_template_kara_enchants_100.sql
src/Bracket_80_2/sql/world/progression_80_2_creature.sql

closes https://github.com/azerothcore/mod-progression-system/issues/322
closes https://github.com/chromiecraft/chromiecraft/issues/5223

fix(db/loot): kara loot progression changes

---

src/Bracket_61_64/sql/world/progression_61_64_dungeon_access_requirements_attunements.sql

the bottom one is the one in game right now. the top one is not in game. this is currently preventing access to SSC. old ID is the id of the unavailable one in this picture and the new ID is the other one.
something similar happens for Hyjal. But here we already had the correct new id in place (13432 instead of 10445)

change ID of SSC attunement quest to match the quest actually available in game

---

src/Bracket_1_19/sql/world/progression_1_19_world_event_Winter_Hats.sql
src/Bracket_61_64/sql/world/progression_1_19_world_event_Winter_Hats_vanilla_down.sql
src/Bracket_71_74/sql/world/progression_1_19_world_event_Winter_Hats_tbc_down.sql

Sourced from Wowhead, used existing Northrend dungeon boss loot as reference. Accounts for both vanilla content and TBC.
Here is the expected loot with this PR:
```
Red:
-  Vanilla
Cannon Master Willey - Strat
Dagran Thaurissan - BRD
War Master Voone - BRS
-  TBC
Botanist Freywinn - Bot
Nethermancer Sepethrea - Mech
Captain Skarloc - Durnholde
-  WotLK
Jedoga Shadowseeker - AK
Grand Magus Telestra - Nexus
Green:
-  Vanilla
Goraluk Anvilcrack - BRS
Darkmaster Gandling - Scholo
Prince Tortheldrin - DM
-  TBC
Grandmaster Vorpil - Slab
Grand Warlock Nethekurse - Shattered Halls
Exarch Maladaar - Crypts
-  WotLK
Mage-Lord Urom - Oculus
```

Add progression stages for Winter Veil's Winter Hats to drop from dungeon bosses.

---

src/Bracket_1_19/sql/world/progression_1_19_love_in_air.sql
src/Bracket_80_1/sql/world/progression_1_19_love_in_air_down.sql

Sourced from Wowhead, used existing Northrend dungeon boss loot as reference. Accounts for vanilla content as the drops were not updated for TBC.
Here is the expected loot with this PR:
```
Red Roses:
-  Vanilla
Princess Moira Bronzebeard - Blackrock Depths
Archivist Galford - Stratholme
Lorekeeper Polkelt - Scholomance
Illyanna Ravenoak - Dire Maul
-  WotLK
Prince Keleseth - Utgarde Keep
Maiden of Grief - Halls of Stone
Prince Taldaram - Ahn'kahet: The Old Kingdom
Ebon Roses:
-  WotLK
Prince Keleseth - Utgarde Keep
Maiden of Grief - Halls of Stone
Prince Taldaram - Ahn'kahet: The Old Kingdom
```

Add progression stages for Love is in the Air's Bouquets of Red Roses to drop from dungeon bosses.

---

src/Bracket_70_3_1/sql/world/progression_61_64_disables_quest_BT_attunement_down.sql
src/Bracket_70_4_1/sql/world/progression_61_64_disables_quest_BT_attunement_down.sql

makes sense as the creature that continues the attunement inhabits SSC

feature(Attunements): allow BT attunement quest on SSC release

---

src/Bracket_70_2_1/sql/world/progression_0_creature_loot_template_Badge_of_Justice_Phase1.sql
src/Bracket_70_5/sql/world/progression_0_creature_loot_template_Badge_of_Justice_Phase1_down.sql

fixes https://github.com/chromiecraft/chromiecraft/issues/6749
fixes https://github.com/azerothcore/mod-progression-system/issues/386

fix(DB/TheEye): remove boj from drops

---

src/Bracket_70_3_2/sql/world/progression_61_64_dungeon_access_requirements_attunements_down_2a.sql
src/Bracket_70_4_1/sql/world/progression_61_64_dungeon_access_requirements_attunements_down_2.sql
src/Bracket_70_4_1/sql/world/progression_61_64_dungeon_access_requirements_attunements_down_2b.sql

SSC no longer needs attunement during the Eye phase
we might want to revert this back at some point tho

feature(T5): split attunement requirement for SSC

---

src/Bracket_70_6_1/sql/world/progression_70_3_1_loot_t5_down.sql

According to https://wowpedia.fandom.com/wiki/Patch_2.4.0#Dungeons_and_raids we already see 3 tokens dropping on bosses when sunwell hits
**required: https://github.com/azerothcore/azerothcore-wotlk/pull/18682**
- Closes https://github.com/chromiecraft/chromiecraft/issues/6969
- Closes https://github.com/chromiecraft/chromiecraft/issues/6973

fix(loot): make Hyjal drop less tokens and restore 3 tokens on sunwell

---

src/Bracket_70_5/sql/world/progression_70_5_amani_war_bear_loot.sql
src/Bracket_71_74/sql/world/progression_70_5_amani_war_bear_loot_down.sql

Adds Amani War Bear to the various prisoner loot game objects. Gets added with Zul'Aman release bracket, removed with first Northrend content bracket (71-74).
Not to be merged prior to [AC PR](https://github.com/azerothcore/azerothcore-wotlk/pull/18869).

Add progression stages for Zul'Aman's prisoner loot.

---

src/Bracket_1_19/scripts/events/midsummer.cpp
src/Bracket_1_19/sql/world/progression_1_19_world_event_Ahune.sql
src/Bracket_80_1/sql/world/progression_1_19_world_event_Ahune_down.sql

Did not test this, no idea if it works.
Aims to close https://github.com/chromiecraft/chromiecraft/issues/7140.

Redo Ahune Ice Stone progression script.

---

src/Bracket_50_59_2/scripts/BlackrockSpire/instance_blackrock_spire.cpp
src/Bracket_60_2_1/scripts/OnyxiasLair/instance_onyxias_lair.cpp

MinionData const minionData[]  is missing a {0, 0} entry to stop reading 
See `void InstanceScript::LoadMinionData(const MinionData* data)`
- https://github.com/azerothcore/azerothcore-wotlk/blob/fe206c71385aac5e12e13f436baa9273885ca3f2/src/server/game/Instances/InstanceScript.cpp#L166
same for creatureData[]

fix: instance buffer overflow

---

src/ProgressionSystem.h

Introduced a new entry '70_6_3' to the ProgressionBracketsNames array to support an additional progression bracket.

Add new progression bracket '70_6_3'
